---
- name: deploy cloudwatch exporter
  hosts: "localhost"
  become: true
  become_user: root
  vars:
    hosts: localhost
  pre_tasks:
  roles:
    - role: ansible-role-java
      java_packages:
        - openjdk-8-jdk
    - role: ansible-vmagent
      vmagent_remote_write:
        - url: <REMOTE-WRITE-URL> -remoteWrite.basicAuth.username=<USERNAME> -remoteWrite.basicAuth.password=<PASSWORD>
      vmagent_global:
        scrape_interval: 60s
        scrape_timeout: 30s
        external_labels:
          asserts_tenant: <ASSERTS-TENANT>
          asserts_env: <ENVIRONMENT-NAME>
      vmagent_scrape_configs:
        - job_name: vmagent
          static_configs:
          - targets:
            - localhost:8429
        - job_name: aws-exporter
          metrics_path: '/aws-exporter/actuator/prometheus'
          static_configs:
          - targets:
            - localhost:8010
          metricRelabelings:
          - sourceLabels: [__name__, region]
            regex: aws_.+;(.+)
            targetLabel: asserts_site
            action: replace
            replacement: $1

  post_tasks:
    - name: Run the exporter
      shell: |
        cd AWS_EXPORTER_DIRECTORY_NAME/
        cp conf/cloudwatch_scrape_config_sample.yml .
        mv cloudwatch_scrape_config_sample.yml cloudwatch_scrape_config.yml
        bin/aws-cloudwatch-exporter &
        exit 0